<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b378a812-2ddf-48a8-b2dd-1b79722b51aa</testSuiteGuid>
   <testCaseLink>
      <guid>9b235a97-c62e-4d74-85f8-408d83d75eef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTesting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e7d46f41-fe71-41ea-9210-595385b39154</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e7d46f41-fe71-41ea-9210-595385b39154</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>e9a04a99-5df1-4d66-917a-d956c5332189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e7d46f41-fe71-41ea-9210-595385b39154</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>d945375e-f403-4fa9-9d7d-96699ee89a98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0858296f-be69-43fa-adad-c072f5d015f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e7d481-cd35-475d-9ef7-cf94ba519016</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
